#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# if git rev-parse --verify HEAD >/dev/null 2>&1
# then
# 	against=HEAD
# else
# 	# Initial commit: diff against an empty tree object
# 	against=3c5ca634bad419ec067955a1ea29f70467ef2b35
# fi

# Redirect output to stderr.
exec 1>&2

# SFTP_EXISTS=$(git diff --cached --name-status | grep "SFTP.sublime-settings")
LICENSES=$(grep -rl '^[[:space:]]*"product_key":[[:space:]]*".*"[,]\?' * --include="*.sublime-settings")

# Use git diff-index to check for licenses
echo "pre-commit: Testing for licenses..."
if  [[ -n $LICENSES ]]
then
	echo "Licenses found for the following files:\n${LICENSES}"
    echo "pre-commit: Aborting! Please remove license information!"
    exit 1
else
    echo "pre-commit: No errors."
    exit 0
fi