tap 'homebrew/bundle'
tap 'caskroom/fonts'

# Essentials
brew 'git'
brew 'zsh'

# Shell stuff
brew 'zsh-completions'
brew 'shellcheck'
brew 'tmux'
brew 'reattach-to-user-namespace'

# Web
brew 'httpie'
brew 'wget'

# Casks
cask 'font-menlo-for-powerline'
cask 'font-inconsolata-g'
cask 'font-inconsolata-g-for-powerline'